/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ITSE;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author ammararshad
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Connect();
    }
    Connection con;
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    String username,name;
    public void Connect(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ITSE?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            st = con.createStatement();}
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());} 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formP = new javax.swing.JPanel();
        pswdL = new javax.swing.JLabel();
        regB = new javax.swing.JButton();
        loginB = new javax.swing.JButton();
        pswdPF = new javax.swing.JPasswordField();
        userNameTF = new javax.swing.JTextField();
        usernameL = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        logoP1 = new javax.swing.JPanel();
        logoTextL2 = new javax.swing.JLabel();
        formL2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));

        formP.setBackground(new java.awt.Color(255, 255, 255));

        pswdL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pswdL.setText("Password:");

        regB.setBackground(new java.awt.Color(255, 255, 255));
        regB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        regB.setText("Register");
        regB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBActionPerformed(evt);
            }
        });

        loginB.setBackground(new java.awt.Color(255, 255, 255));
        loginB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginB.setText("Login");
        loginB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });

        pswdPF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N

        userNameTF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N
        userNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTFActionPerformed(evt);
            }
        });

        usernameL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameL.setText("Username:");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.setBorder(null);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        logoP1.setBackground(new java.awt.Color(102, 0, 102));

        logoTextL2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        logoTextL2.setForeground(new java.awt.Color(255, 255, 255));
        logoTextL2.setText("HUMAN RESOURCE MANAGEMENT SYSTEM");

        formL2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        formL2.setForeground(new java.awt.Color(255, 255, 255));
        formL2.setText("LOGIN FORM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/output-onlinepngtools.png"))); // NOI18N

        javax.swing.GroupLayout logoP1Layout = new javax.swing.GroupLayout(logoP1);
        logoP1.setLayout(logoP1Layout);
        logoP1Layout.setHorizontalGroup(
            logoP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoP1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(logoP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formL2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoTextL2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoP1Layout.setVerticalGroup(
            logoP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoP1Layout.createSequentialGroup()
                .addGroup(logoP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logoP1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(logoTextL2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formL2))
                    .addGroup(logoP1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginB1.setBackground(new java.awt.Color(255, 255, 255));
        loginB1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginB1.setText("Forget Password");
        loginB1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPLayout = new javax.swing.GroupLayout(formP);
        formP.setLayout(formPLayout);
        formPLayout.setHorizontalGroup(
            formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameL)
                    .addComponent(pswdL))
                .addGap(52, 52, 52)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(formPLayout.createSequentialGroup()
                        .addComponent(regB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pswdPF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
            .addComponent(logoP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginB1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        formPLayout.setVerticalGroup(
            formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPLayout.createSequentialGroup()
                .addComponent(logoP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameL))
                .addGap(18, 18, 18)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswdPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswdL))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(52, 52, 52)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regB, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(loginB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(loginB1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(formP, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTFActionPerformed

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        //Login Button.
        String username = userNameTF.getText();
        String pswd=pswdPF.getText();
        
        try{
            String sql = "select * from registration where `Employee ID`='"+username+"' and `Password`='"+pswd+"'";
            rs = st.executeQuery(sql);

            if(rs.next()){
                name = rs.getString("Name");
                JOptionPane.showMessageDialog(this,"Welcome \""+name+"\"");
                //setVisible(false);
                
                
                //Dashboard
                Dashboard dashboard = new Dashboard();// Object of Registration Form (Aggregation)
                dashboard.nam(name,username);//To show Name Of the Employee
                dashboard.show();//Show Dashboard
                dispose();//Close Login
            }
            else{
                JOptionPane.showMessageDialog(this,"Invalid Login Credentials , Try Again");}}
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_loginBActionPerformed

    private void regBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBActionPerformed
        //Registration Button. It takes to the registration page.
        Registration registration=new Registration();// Object of Registration Form (Aggregation)
        registration.show();// Go to Registration Form
        dispose();// Close the Login Form
    }//GEN-LAST:event_regBActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            pswdPF.setEchoChar((char)0);
            jCheckBox1.setText("Hide Password");
        }
        else
        {
            pswdPF.setEchoChar('*');
            jCheckBox1.setText("Show Password");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void loginB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginB1ActionPerformed
        // TODO add your handling code here:
        String user = userNameTF.getText();
        String pswd;
        if(user.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter your User Name First");
        }
        else
        {
            try{
            String sql = "select * from registration where `Employee ID`='"+user+"'";
            rs = st.executeQuery(sql);

            if(rs.next()){
                pswd = rs.getString("Password");
                JOptionPane.showMessageDialog(this,"Your Password is :  \""+pswd+"\"");
                
            }
            else{
                JOptionPane.showMessageDialog(this,"There is no Record with this Username");}}
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());} 
        }
    }//GEN-LAST:event_loginB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel formL2;
    private javax.swing.JPanel formP;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginB;
    private javax.swing.JButton loginB1;
    private javax.swing.JPanel logoP1;
    private javax.swing.JLabel logoTextL2;
    private javax.swing.JLabel pswdL;
    private javax.swing.JPasswordField pswdPF;
    private javax.swing.JButton regB;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JLabel usernameL;
    // End of variables declaration//GEN-END:variables
}
