/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITSE;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bilal
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        Connect();
        this.setLocationRelativeTo(null);
    }
    Connection con;
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    String username;
    public void Connect(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ITSE?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            st = con.createStatement();}
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());} 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoP = new javax.swing.JPanel();
        logoTextL = new javax.swing.JLabel();
        logoL = new javax.swing.JLabel();
        formL = new javax.swing.JLabel();
        formP = new javax.swing.JPanel();
        usernameL = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        pswdL = new javax.swing.JLabel();
        loginB = new javax.swing.JButton();
        regB = new javax.swing.JButton();
        pswdPF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoP.setBackground(new java.awt.Color(0, 102, 51));

        logoTextL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logoTextL.setForeground(new java.awt.Color(255, 255, 255));
        logoTextL.setText("Human Resource Management System");

        logoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-employee-60.png"))); // NOI18N

        formL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formL.setForeground(new java.awt.Color(255, 102, 0));
        formL.setText("Login Form");

        javax.swing.GroupLayout logoPLayout = new javax.swing.GroupLayout(logoP);
        logoP.setLayout(logoPLayout);
        logoPLayout.setHorizontalGroup(
            logoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPLayout.createSequentialGroup()
                .addComponent(logoL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(logoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logoPLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(logoTextL))
                    .addGroup(logoPLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(formL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPLayout.setVerticalGroup(
            logoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(logoTextL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formL)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(logoPLayout.createSequentialGroup()
                .addComponent(logoL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        formP.setBackground(new java.awt.Color(102, 102, 0));

        usernameL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameL.setForeground(new java.awt.Color(255, 255, 255));
        usernameL.setText("Username:");

        userNameTF.setBackground(new java.awt.Color(153, 153, 0));
        userNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTFActionPerformed(evt);
            }
        });

        pswdL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pswdL.setForeground(new java.awt.Color(255, 255, 255));
        pswdL.setText("Password:");

        loginB.setBackground(new java.awt.Color(255, 102, 0));
        loginB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginB.setForeground(new java.awt.Color(255, 255, 255));
        loginB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-24.png"))); // NOI18N
        loginB.setText("Login");
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });

        regB.setBackground(new java.awt.Color(255, 102, 0));
        regB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regB.setForeground(new java.awt.Color(255, 255, 255));
        regB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-registration-24.png"))); // NOI18N
        regB.setText("Register");
        regB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBActionPerformed(evt);
            }
        });

        pswdPF.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout formPLayout = new javax.swing.GroupLayout(formP);
        formP.setLayout(formPLayout);
        formPLayout.setHorizontalGroup(
            formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameL)
                    .addComponent(pswdL))
                .addGap(26, 26, 26)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameTF)
                    .addComponent(pswdPF))
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(loginB)
                .addGap(102, 102, 102)
                .addComponent(regB)
                .addGap(0, 160, Short.MAX_VALUE))
        );
        formPLayout.setVerticalGroup(
            formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameL)
                    .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswdL)
                    .addComponent(pswdPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginB)
                    .addComponent(regB))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(formP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTFActionPerformed

    private void regBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBActionPerformed
        //Registration Button. It takes to the registration page.
        RegistrationForm registrationForm=new RegistrationForm();// Object of Registration Form (Aggregation)
        registrationForm.show();// Go to Registration Form
        dispose();// Close the Login Form
    }//GEN-LAST:event_regBActionPerformed

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        //Login Button.
        String username = userNameTF.getText();
        String pswd=pswdPF.getText();
        try{
            String sql = "select * from registration where `Employee ID`='"+username+"' and `Password`='"+pswd+"'";
            rs = st.executeQuery(sql);

            if(rs.next()){
                JOptionPane.showMessageDialog(this,"Login Successful");
                setVisible(false);
                /*Dashboard dashboard = new Dashboard();// Object of Registration Form (Aggregation)
                obj.setVisible(true);//Show Dashboard*/}
            else{
                JOptionPane.showMessageDialog(this,"Invalid Login Credentials , Try Again");}}
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_loginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel formL;
    private javax.swing.JPanel formP;
    private javax.swing.JButton loginB;
    private javax.swing.JLabel logoL;
    private javax.swing.JPanel logoP;
    private javax.swing.JLabel logoTextL;
    private javax.swing.JLabel pswdL;
    private javax.swing.JPasswordField pswdPF;
    private javax.swing.JButton regB;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JLabel usernameL;
    // End of variables declaration//GEN-END:variables
}
