/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ITSE;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author ammararshad
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    String name,dep,des,pswd,cpswd,empId,email,dob;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoP = new javax.swing.JPanel();
        logoL = new javax.swing.JLabel();
        logoTextL2 = new javax.swing.JLabel();
        formL2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        formP = new javax.swing.JPanel();
        nameL = new javax.swing.JLabel();
        dobL = new javax.swing.JLabel();
        emailL = new javax.swing.JLabel();
        empIdL = new javax.swing.JLabel();
        depL = new javax.swing.JLabel();
        desL = new javax.swing.JLabel();
        pswdL = new javax.swing.JLabel();
        cpswdL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        empIdTF = new javax.swing.JTextField();
        depTF = new javax.swing.JTextField();
        desTF = new javax.swing.JTextField();
        dobDC = new com.toedter.calendar.JDateChooser();
        emailCB = new javax.swing.JComboBox<>();
        regB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        pswdPF = new javax.swing.JPasswordField();
        cpswdPF = new javax.swing.JPasswordField();
        errorL = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 720));

        logoP.setBackground(new java.awt.Color(102, 0, 102));

        logoTextL2.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        logoTextL2.setForeground(new java.awt.Color(255, 255, 255));
        logoTextL2.setText("HUMAN RESOURCE MANAGEMENT SYSTEM");

        formL2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        formL2.setForeground(new java.awt.Color(255, 255, 255));
        formL2.setText("REGISTRATION FORM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/output-onlinepngtools.png"))); // NOI18N

        javax.swing.GroupLayout logoPLayout = new javax.swing.GroupLayout(logoP);
        logoP.setLayout(logoPLayout);
        logoPLayout.setHorizontalGroup(
            logoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(logoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoTextL2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formL2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(logoL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPLayout.setVerticalGroup(
            logoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(logoPLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(logoL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(logoPLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(logoTextL2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formL2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formP.setBackground(new java.awt.Color(255, 255, 255));

        nameL.setBackground(new java.awt.Color(0, 0, 0));
        nameL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameL.setText("Name:");

        dobL.setBackground(new java.awt.Color(0, 0, 0));
        dobL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobL.setText("DOB:");

        emailL.setBackground(new java.awt.Color(0, 0, 0));
        emailL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailL.setText("E-mail:");

        empIdL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        empIdL.setText("Employee ID:");

        depL.setBackground(new java.awt.Color(0, 0, 0));
        depL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        depL.setText("Department:");

        desL.setBackground(new java.awt.Color(0, 0, 0));
        desL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        desL.setText("Designation:");

        pswdL.setBackground(new java.awt.Color(0, 0, 0));
        pswdL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pswdL.setText("Password:");

        cpswdL.setBackground(new java.awt.Color(0, 0, 0));
        cpswdL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cpswdL.setText("Confirm Password:");

        nameTF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        nameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTFKeyPressed(evt);
            }
        });

        emailTF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N

        empIdTF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N
        empIdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empIdTFKeyPressed(evt);
            }
        });

        depTF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N
        depTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                depTFKeyPressed(evt);
            }
        });

        desTF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N
        desTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                desTFKeyPressed(evt);
            }
        });

        dobDC.setBackground(new java.awt.Color(255, 255, 255));

        emailCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@hotmail.com", "@yahoo.com", "@outlook.com" }));

        regB.setBackground(new java.awt.Color(255, 255, 255));
        regB.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        regB.setText("Register");
        regB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBActionPerformed(evt);
            }
        });

        cancelB.setBackground(new java.awt.Color(255, 255, 255));
        cancelB.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cancelB.setText("Cancel");
        cancelB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        pswdPF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N

        cpswdPF.setFont(new java.awt.Font("Sitka Small", 3, 11)); // NOI18N

        errorL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorL.setForeground(new java.awt.Color(255, 0, 0));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Show");
        jCheckBox2.setBorder(null);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show");
        jCheckBox1.setBorder(null);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPLayout = new javax.swing.GroupLayout(formP);
        formP.setLayout(formPLayout);
        formPLayout.setHorizontalGroup(
            formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPLayout.createSequentialGroup()
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(regB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameL)
                            .addComponent(emailL)
                            .addComponent(cpswdL)
                            .addComponent(empIdL)
                            .addComponent(depL)
                            .addComponent(desL)
                            .addComponent(pswdL)
                            .addComponent(dobL))
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(empIdTF)
                                            .addComponent(dobDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(depTF)
                                            .addComponent(desTF)
                                            .addComponent(pswdPF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(formPLayout.createSequentialGroup()
                                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailCB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(cpswdPF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addComponent(errorL, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formPLayout.setVerticalGroup(
            formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPLayout.createSequentialGroup()
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(errorL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameL))
                        .addGap(18, 18, 18)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailL))
                            .addComponent(emailCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobL))
                        .addGap(9, 9, 9)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empIdL))
                        .addGap(18, 18, 18)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depL))
                        .addGap(18, 18, 18)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(desTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desL))
                        .addGap(18, 18, 18)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pswdPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pswdL))
                        .addGap(18, 18, 18)
                        .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpswdPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpswdL)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addGroup(formPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(formP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(logoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void nameTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTFKeyPressed
        //Validation check for name. Contains only alphabets.
        char c=evt.getKeyChar();
        String shift;
        if((c>=65&&c<=90)||(c>=97&&c<=122)||Character.isISOControl(c)||(c==14&&c==15)||(evt.getKeyCode()==KeyEvent.VK_SHIFT||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_SPACE)){}
        else{
            JOptionPane.showMessageDialog(null,"Enter alphabets only.");}
    }//GEN-LAST:event_nameTFKeyPressed

    private void empIdTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empIdTFKeyPressed
        //Validation check for Employee ID. Contains only alphabets, digits and dash(-).
        char c=evt.getKeyChar();
        if((c>=65&&c<=90)||(c>=97&&c<=122)||(c>=48&&c<=57)||c==45||Character.isISOControl(c)||KeyEvent.VK_SHIFT==evt.getKeyCode()||KeyEvent.VK_LEFT==evt.getKeyCode()||KeyEvent.VK_RIGHT==evt.getKeyCode()||evt.getKeyCode()==KeyEvent.VK_SPACE){}
        else{
            JOptionPane.showMessageDialog(null,"Enter alphabets, digits and dash(-) only.");}
    }//GEN-LAST:event_empIdTFKeyPressed

    private void depTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depTFKeyPressed
        //Validation check for department name. Contains only alphabets.
        char c=evt.getKeyChar();
        if((c>=65&&c<=90)||(c>=97&&c<=122)||Character.isISOControl(c)||(c==14&&c==15)||KeyEvent.VK_SHIFT==evt.getKeyCode()||KeyEvent.VK_LEFT==evt.getKeyCode()||KeyEvent.VK_RIGHT==evt.getKeyCode()||evt.getKeyCode()==KeyEvent.VK_SPACE){}
        else{
            JOptionPane.showMessageDialog(null,"Enter alphabets only.");}
    }//GEN-LAST:event_depTFKeyPressed

    private void desTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desTFKeyPressed
        //Validation check for designation. Contains only alphabets, digits and dash(-).
        char c=evt.getKeyChar();
        if((c>=65&&c<=90)||(c>=97&&c<=122)||(c>=48&&c<=57)||c==45||Character.isISOControl(c)||KeyEvent.VK_SHIFT==evt.getKeyCode()||KeyEvent.VK_LEFT==evt.getKeyCode()||KeyEvent.VK_RIGHT==evt.getKeyCode()||evt.getKeyCode()==KeyEvent.VK_SPACE){}
        else{
            JOptionPane.showMessageDialog(null,"Enter alphabets, digits and dash(-) only.");}
        // TODO add your handling code here:
    }//GEN-LAST:event_desTFKeyPressed

    private void regBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBActionPerformed
        // Register Button. It registers the user and return to the Login Form.
        name=nameTF.getText();
        dep=depTF.getText();
        des=desTF.getText();
        email=emailTF.getText();
        empId=empIdTF.getText();
        pswd=pswdPF.getText();
        cpswd=cpswdPF.getText();
        SimpleDateFormat sdf = new SimpleDateFormat();
        dob=sdf.format(dobDC.getDate());
        String disc =String.valueOf(dobDC.getDate());
        //dob=String.valueOf(dobDC.getDate());
        if(name.equals("")||dep.equals("")||des.equals("")||email.equals("")||empId.equals("")||disc.equals("")||pswd.equals("")||cpswd.equals("")){
            JOptionPane.showMessageDialog(this,"Fields should not be empty.");}
        else{
            if(!((pswd.equals(cpswd))&&(pswd.length()>=6))){
                JOptionPane.showMessageDialog(null,"Password does not match or contains less than 6 characters.");
            }
            else{
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ITSE?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                    ps=con.prepareStatement("INSERT INTO `registration`(`Name`, `DOB`, `Email`, `Employee ID`, `Department`, `Designation`, `Password`) VALUES (?,?,?,?,?,?,?)");
                    ps.setString(1, name);
                    ps.setString(2, dob);
                    ps.setString(3, email+emailCB.getSelectedItem());
                    ps.setString(4, empId);
                    ps.setString(5, dep);
                    ps.setString(6, des);
                    ps.setString(7, cpswd);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Saved Successfully.");
                    Login login=new Login();// Object of Login Form (Aggregation)
                    login.show();// Return to Login Form
                    dispose();}// Close the Registration Form
                catch(ClassNotFoundException ex){
                    java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);}
                catch (SQLException ex){
                    java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}}}
    }//GEN-LAST:event_regBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        //Cancel Button. It clear all the text fields.
        nameTF.setText("");
        emailTF.setText("");
        empIdTF.setText("");
        depTF.setText("");
        desTF.setText("");
        pswdPF.setText("");
        cpswdPF.setText("");
        Login login=new Login();// Object of Login Form (Aggregation)
        login.show();// Return to Login Form
        dispose();// Close the Registration Form
    }//GEN-LAST:event_cancelBActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            pswdPF.setEchoChar((char)0);
            jCheckBox1.setText("Hide");
        }
        else
        {
            pswdPF.setEchoChar('*');
            jCheckBox1.setText("Show");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox2.isSelected())
        {
            cpswdPF.setEchoChar((char)0);
            jCheckBox2.setText("Hide");
        }
        else
        {
            cpswdPF.setEchoChar('*');
            jCheckBox2.setText("Show");
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel cpswdL;
    private javax.swing.JPasswordField cpswdPF;
    private javax.swing.JLabel depL;
    private javax.swing.JTextField depTF;
    private javax.swing.JLabel desL;
    private javax.swing.JTextField desTF;
    private com.toedter.calendar.JDateChooser dobDC;
    private javax.swing.JLabel dobL;
    private javax.swing.JComboBox<String> emailCB;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel empIdL;
    private javax.swing.JTextField empIdTF;
    private javax.swing.JLabel errorL;
    private javax.swing.JLabel formL2;
    private javax.swing.JPanel formP;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoL;
    private javax.swing.JPanel logoP;
    private javax.swing.JLabel logoTextL2;
    private javax.swing.JLabel nameL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel pswdL;
    private javax.swing.JPasswordField pswdPF;
    private javax.swing.JButton regB;
    // End of variables declaration//GEN-END:variables
}
